# Generated by Django 4.2.17 on 2024-12-27 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the search', unique=True)),
                ('query', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('results_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Users who have access to this search', related_name='shared_searches', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'searches',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the business', unique=True)),
                ('business_id', models.CharField(help_text='Unique identifier from Google Maps', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('place_id', models.CharField(blank=True, help_text='Google Maps Place ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='scraper.search')),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['-timestamp'], name='scraper_sea_timesta_7216a8_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['user'], name='scraper_sea_user_id_9f079b_idx'),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['uuid'], name='scraper_sea_uuid_652ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['-created_at'], name='scraper_bus_created_cc0dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_id'], name='scraper_bus_busines_950851_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['search'], name='scraper_bus_search__f27322_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['uuid'], name='scraper_bus_uuid_ec95a6_idx'),
        ),
    ]
