# Generated by Django 4.2.17 on 2024-12-29 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='business',
            name='scraper_bus_busines_950851_idx',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_id',
        ),
    ]
