# Generated by Django 4.2.17 on 2024-12-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_search_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='search_history',
            field=models.ManyToManyField(related_name='historical_results', to='scraper.search'),
        ),
    ]
