# Generated by Django 4.2.17 on 2024-12-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_business_search_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
